spring:
  cloud:
    function:
      definition: aggregateMessagesPerChatRoom
    stream:
      kafka:
        streams:
          bindings:
            aggregateMessagesPerChatRoom-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.example.chatroomskafkabackendprocessor.converter.ChatMessageSerDes

          binder:
            configuration:
              commit.interval.ms: 2000
        binder:
          brokers:
            - localhost:9092
        bindings:
          aggregateMessagesPerChatRoom-in-0:
            consumer:
              configuration:
                group-id: my-consumer-group
                value:
                  deserializer: com.example.chatroomskafkabackendprocessor.converter.ChatMessageSerDes
          aggregateMessagesPerChatRoom-out-0:
            consumer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.LongSerializer

      bindings:
        aggregateMessagesPerChatRoom-in-0:
          destination: chat-room-topic
        aggregateMessagesPerChatRoom-out-0:
          destination: chat-room-aggregator-messages-per-room